### ISSUE TITLE
File dates are 12/31/2097

### ISSUE THREAD

**Issue by pejacoby** [LyndLabs/Wardriver#10]
Files produced with the 1.1 alpha code are presenting in the file system with a created and modified date of "12/31/2097 11:00pm"

The datestamp in the filename is correct "DNS_Driveby_2023-098-14_0.csv"

**Comment by AlexLynd** [comment]
oof I'll take a look at this, thanks for pointing that out!  I'll also publicly release the v1.1 binary :)

**Comment by pejacoby** [comment]
FYI I had a run later in the day and the file date recorded as 01/01/2098, so some threshold was crossed from the base epoch.  See attached screenshot.
<img width="558" alt="DNSdriveby-date010198" src="https://github.com/LyndLabs/Wardriver/assets/16978661/4d94deba-a5d1-45c8-bde4-df168ae6d9db">

**Comment by lukeswitz** [comment]
> oof I'll take a look at this, thanks for pointing that out! I'll also publicly release the v1.1 binary :)

Any news on this?

**Comment by pejacoby** [comment]
Good point @AlexLynd this is indeed your fork of the code, I posted to the wrong Git.  Currently running 1.2alpha and seeing the same.

**Comment by AlexLynd** [comment]
Hey @pejacoby, try out the latest `v1.2` binary, all other issues with instability & bootloops should be fixed!

**Comment by pejacoby** [comment]
Not seeing any file date difference with your 1.2 release. Also seeing all located APs repeated on each scan cycle in the CsV file, with the total count displayed going up by that increment each scan. So not any better here.
